# name: Check DMV Availability

# on:
#   schedule:
#     - cron: "*/10 * * * *" # every 10 minutes
#   workflow_dispatch: # allows manual trigger

# jobs:
#   check:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Set up Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm install

#       - name: Run checker
#         run: node index.js
#         env:
#           EMAIL_USER: ${{ secrets.EMAIL_USER }}
#           EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
#           EMAIL_TO: ${{ secrets.EMAIL_TO }}
